//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidhyalaya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherInSubject
    {
        public int TeacherSubjectId { get; set; }
        public int UserId { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
